MITReportInterface/urls.py
from django.urls import path
from . import views

app_name = 'MITReportInterface'

urlpatterns = [
    # ex: /MITReportInterface
    path("", views.home, name="home"),

    # ex: /MITReportInterface/reportInformation
    path("reportInformation/", views.reportInformation, name="reportInformation"),

    # ex: /MITReportInterface/mit
    path("reportView/", views.reportViewer, name="reportView"),
    path("downloadReport/", views.downloadReport, name="downloadReport"),
    path('web/admin/home/', views.home, name='home'),
    path('web/admin/list/', views.list_merchants, name='list_merchants'),
    path('web/admin/new/', views.new_merchant, name='new_merchant'),
    path('web/admin/test/', views.test_merchant, name='test_merchant'),
    path('web/admin/search/', views.search_transactions, name='search_transactions'),
    path('edit/<int:merchant_id>/', views.edit_merchant, name='edit_merchant'),
    path('delete/<int:merchant_id>/', views.delete_merchant, name='delete_merchant'),
    path('view/<int:merchant_id>/', views.view_merchant, name='view_merchant'),
    path('admin_tools/', views.home, name='admin_tools'),
]

ShopMIT_Services/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reports/', include('MITReportInterface.urls', namespace='MITReportInterface')),
    path('', include('MITReportInterface.urls')),
]

MITReportInterface/models.py
from django.db import models

class Merchant(models.Model):
    id = models.AutoField(primary_key=True)
    merchant_id = models.CharField(max_length=100, unique=True, default='default_merchant_id')
    orderpage_transaction_type = models.CharField(max_length=20, choices=[("sale", "Sale"), ("authorization", "Authorization")], default='sale')
    test_mode = models.BooleanField(choices=[(True, "Submit Orders to the Cybersource test system."), (False, "Submit Orders to the Cybersource production system.")], default=True)
    disable_captcha = models.BooleanField(default=False)
    disabled = models.BooleanField(default=False)
    cancellation_date = models.DateField(null=True, blank=True)
    secure_acceptance_status = models.CharField(max_length=100, blank=True)
    has_sa_keys = models.BooleanField(default=False)
    has_p12_keys = models.BooleanField(default=False)
    has_soap_keys = models.BooleanField(default=False)
    has_scmp_keys = models.BooleanField(default=False)
    notes = models.TextField(blank=True)
    profile_id = models.CharField(max_length=100, blank=True)
    access_key = models.CharField(max_length=100, blank=True)
    confirmation_settings = models.CharField(max_length=100, blank=True)
    pricing_information = models.DecimalField(max_digits=10, decimal_places=2, default=1.00)
    billing_information = models.CharField(max_length=255, blank=True)
    additional_information = models.CharField(max_length=255, blank=True)

MITReportInterface/views.py
from django.http import HttpResponse, FileResponse
from django.template import loader
from .reportDownload import process_get
import csv
import os
import xmltodict
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Merchant
from datetime import datetime
from django import forms

# Create your views here.


def index(request):
    template = loader.get_template("MITReportInterface/index.html")
    context = {}
    return HttpResponse(template.render(context, request))


def reportInformation(request):
    template = loader.get_template("MITReportInterface/reportInfo.html")
    merchant_ID = request.GET['merchant_ID']
    context = {
        'merchantID': merchant_ID
    }
    return HttpResponse(template.render(context, request))


def reportViewer(request):
    template = loader.get_template("MITReportInterface/reportView.html")
    context = {
        'ReportHeaders': [],
        'Requests': [],
        'Error_Report': ''
    }

    startDate = request.GET['start_date']
    endDate = request.GET['end_date']
    merchant_ID = request.GET['merchant_ID']

    downloadStatus, reportDict = process_get()


    if downloadStatus == 200:
        if reportDict['Report']['Requests'] is not None:
            for req in reportDict['Report']['Requests']['Request']:
                currentRequest = {}
                currentRequest.update(getMerchantInfo(reportDict['Report']))
                currentRequest.update(getRequestInfo(req))
                currentRequest.update(getBillingInfo(req['BillTo']))
                currentRequest.update(getShippingInfo(req['ShipTo']))
                #currentRequest.update(getCardInfo(req['PaymentMethod']['Card']))
                currentRequest.update(getCardInfo(req.get('PaymentMethod').get('Card')))
                currentRequest.update(getLineItems(req['LineItems']['LineItem']))
                context['Requests'].append(currentRequest)
                context['ReportHeaders'] = list(currentRequest.keys())
        else:
            currentRequest = {}
            currentRequest.update(getMerchantInfo(reportDict['Report']))
            currentRequest.update(getRequestInfo({}))
            currentRequest.update(getBillingInfo({}))
            currentRequest.update(getShippingInfo({}))
            currentRequest.update(getCardInfo({}))
            currentRequest.update(getLineItems({}))
            context['Requests'].append(currentRequest)
            context['ReportHeaders'] = list(currentRequest.keys())

        for i, req in enumerate(context['Requests']):
            for attribute in req.keys():
                if context['Requests'][i][attribute] is None:
                    context['Requests'][i][attribute] = ''

    else:
        context['Error_Report'] = 'An error occured when downloading desired report'

    return HttpResponse(template.render(context, request))

def downloadReport(request):
    pass



# Helper Function To extract merchant info from report
def getMerchantInfo(reportDict):
    merchantInfo = {}

    merchantInfo['Report Name'] = reportDict['@Name']
    merchantInfo['OrganizationID'] = reportDict['@OrganizationID']
    # should I use localized request date

    return merchantInfo


def getRequestInfo(requestDict):
    if requestDict == None:
        requestDict = {}
    requestInfo = {}
    requestInfo['Request Date'] = requestDict.get('@LocalizedRequestDate')
    requestInfo['Request ID'] = requestDict.get('@RequestID')
    requestInfo['Source'] = requestDict.get('@Source')
    requestInfo['Subscription ID'] = requestDict.get('@SubscriptionID')
    #requestInfo.update(getBillingInfo(requestDict['BillTo']))

    return requestInfo


def getBillingInfo(requestDict):
    if requestDict == None:
        requestDict = {}
    billingInfo = {}
    billingInfo['BillTo Address1'] = requestDict.get('Address1')
    billingInfo['BillTo Address2'] = requestDict.get('Address2')
    billingInfo['BillTo City'] = requestDict.get('City')
    billingInfo['BillTo State'] = requestDict.get('State')
    billingInfo['BillTo Company Name'] = requestDict.get('CompanyName')
    billingInfo['BillTo Country'] = requestDict.get('Country')
    billingInfo['BillTo CustomerID'] = requestDict.get('CustomerID')
    billingInfo['BillTo Email'] = requestDict.get('Email')
    billingInfo['BillTo Suffix'] = requestDict.get('NameSuffix')
    billingInfo['BillTo FirstName'] = requestDict.get('FirstName')
    billingInfo['BillTo MiddleName'] = requestDict.get('MiddleName')
    billingInfo['BillTo LastName'] = requestDict.get('LastName')
    billingInfo['BillTo HostName'] = requestDict.get('HostName')
    billingInfo['BillTo IPAddress'] = requestDict.get('IPAddress')
    billingInfo['BillTo Zip'] = requestDict.get('Zip')
    billingInfo['BillTo Phone'] = requestDict.get('Phone')
    billingInfo['BillTo Title'] = requestDict.get('Title')
    billingInfo['BillTo UserName'] = requestDict.get('UserName')
    return billingInfo


def getShippingInfo(requestDict):
    if requestDict == None:
        requestDict = {}
    shippingInfo = {}
    shippingInfo['ShipTo Address1'] = requestDict.get('Address1')
    shippingInfo['ShipTo Address2'] = requestDict.get('Address2')
    shippingInfo['ShipTo City'] = requestDict.get('City')
    shippingInfo['ShipTo Country'] = requestDict.get('Country')
    shippingInfo['ShipTo State'] = requestDict.get('State')
    shippingInfo['ShipTo Zip'] = requestDict.get('Zip')
    shippingInfo['ShipTo Company Name'] = requestDict.get('CompanyName')
    shippingInfo['ShipTo FirstName'] = requestDict.get('FirstName')
    shippingInfo['ShipTo LastName'] = requestDict.get('LastName')
    shippingInfo['ShipToPhone'] = requestDict.get('Phone')
    return shippingInfo


def getCardInfo(requestDict):
    if requestDict == None:
        requestDict = {}
    cardInfo = {}
    cardInfo['Card Type'] = requestDict.get('CardType')
    cardInfo['Card Expiration Month'] = requestDict.get('ExpirationMonth')
    cardInfo['Card Expiration Year'] = requestDict.get('ExpirationYear')
    cardInfo['Card Start Month'] = requestDict.get('StartMonth')
    cardInfo['Card Start Year'] = requestDict.get('StartYear')
    cardInfo['Card Issue Number'] = requestDict.get('IssueNumber')
    cardInfo['Card Account Suffix'] = requestDict.get('AccountSuffix')
    return cardInfo


def getLineItems(requestDict):
    if requestDict == None:
        requestDict = {}
    lineItemInfo = {}
    lineItemInfo['Line Item Number'] = requestDict.get('@Number')
    lineItemInfo['Line Item'] = requestDict.get('FulfillmentType')
    lineItemInfo['Line Item Quantity'] = requestDict.get('Quantity')
    lineItemInfo['Line Item Unit Price'] = requestDict.get('UnitPrice')
    lineItemInfo['Line Item tax amount'] = requestDict.get('TaxAmount')
    lineItemInfo['Line Item SKU'] = requestDict.get('MerchantProductSKU')
    lineItemInfo['Line Item product name'] = requestDict.get('ProductName')
    lineItemInfo['Line Item product code'] = requestDict.get('ProductCode')
    return lineItemInfo


def getReplyInfo(requestDict):
    print(requestDict)
    replyInfo = {}
    replyInfo[''] = requestDict['']

    return replyInfo


def getMerchantDefinedData():
    merchantData = {}

def home(request):
    current_date = datetime.now().strftime("%m/%d/%Y")
    if request.user.is_authenticated:
        user_name = request.user.username
    else:
        user_name = "Guest"

    context = {
        'current_date': current_date,
        'user_name': user_name
    }
    return render(request, 'MITReportInterface/home.html', context)

def list_merchants(request):
    merchants = Merchant.objects.all()
    context = {
        'merchants': merchants,
        'user': request.user,
        'current_date': timezone.now().strftime("%m/%d/%Y"),
    }
    return render(request, 'MITReportInterface/list_merchants.html', context)


class TestMerchantForm(forms.ModelForm):
    class Meta:
        model = Merchant
        fields = [
            'id', 'profile_id', 'access_key', 'confirmation_settings',
            'pricing_information', 'billing_information', 'additional_information'
        ]
        widgets = {
            'id': forms.Select(attrs={'class': 'form-control', 'required': 'required'}),
            'profile_id': forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
            'access_key': forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
            'confirmation_settings': forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
            'pricing_information': forms.NumberInput(attrs={'class': 'form-control', 'min': 1, 'required': 'required'}),
            'billing_information': forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
            'additional_information': forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
        }


def test_merchant(request, merchant_id=None):
    if merchant_id:
        merchant = get_object_or_404(Merchant, pk=merchant_id)
    else:
        merchant = None

    if request.method == 'POST':
        form = TestMerchantForm(request.POST, instance=merchant)
        if form.is_valid():
            form.save()
            return redirect('list_merchants')
    else:
        form = TestMerchantForm(instance=merchant)

    return render(request, 'MITReportInterface/test_merchants.html', {'form': form})


class NewMerchantForm(forms.ModelForm):
    class Meta:
        model = Merchant
        fields = [
            'merchant_id', 'orderpage_transaction_type', 'test_mode', 'disable_captcha'
        ]
        widgets = {
            'merchant_id': forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
            'orderpage_transaction_type': forms.Select(attrs={'class': 'form-control'}),
            'test_mode': forms.Select(choices=[(True, "Test Mode"), (False, "Production Mode")],

MITReportInterface/templates/MITReportInterface/delete_merchant.html
{% extends 'MITReportInterface/base.html' %}

{% block title %}Delete Merchant{% endblock %}

{% block content %}
<h1>Delete Merchant</h1>
<p>Are you sure you want to delete the merchant "{{ merchant.id }}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'MITReportInterface:list_merchants' %}" class="btn btn-secondary ms-2">Cancel</a>
</form>
{% endblock %}

MITReportInterface/templates/MITReportInterface/edit_merchant.html
{% extends 'MITReportInterface/base.html' %}

{% block title %}Edit Merchant{% endblock %}

{% block content %}
<h1>Edit Merchant</h1>
<form method="post">
    {% csrf_token %}
    <!-- Example of form fields using Bootstrap 5.3.3 classes -->
    <div class="mb-3">
        <label for="merchantName" class="form-label">Merchant Name</label>
        <input type="text" class="form-control" id="merchantName" name="merchant_name" required>
    </div>
    <div class="mb-3">
        <label for="merchantEmail" class="form-label">Merchant Email</label>
        <input type="email" class="form-control" id="merchantEmail" name="merchant_email" required>
    </div>
    <div class="mb-3">
        <label for="merchantStatus" class="form-label">Status</label>
        <select class="form-select" id="merchantStatus" name="merchant_status" required>
            <option value="active">Active</option>
            <option value="inactive">Inactive</option>
        </select>
    </div>
    <!-- Add more form fields as needed -->
    <button type="submit" class="btn btn-success">Save</button>
</form>
{% endblock %}
{% block extra_buttons %}
<button type="button" class="btn btn-secondary" onclick="location.href='{% url 'MITReportInterface:home' %}'">Return to Home</button>
{% endblock %}

MITReportInterface/templates/MITReportInterface/home.html
{% extends 'MITReportInterface/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="portlet-font mt-4">
    <div id="hi1" class="mb-3">
        <div id="logo" class="fw-bold">Merchant&nbsp;Services</div>
        <div id="welcome">Welcome Thomas Cole, {{ current_date }}</div>
    </div>
    <div id="mid">
        <div id="nav1"></div>
        <div id="nav2" class="mb-3">
            <h2>Merchant Services Administration</h2>
        </div>
        <div class="content">
            <div class="list-group">
                <a href="{% url 'MITReportInterface:list_merchants' %}" class="list-group-item list-group-item-action">List Merchants</a>
                <a href="{% url 'MITReportInterface:test_merchant' %}" class="list-group-item list-group-item-action">Test Merchant</a>
                <a href="{% url 'MITReportInterface:new_merchant' %}" class="list-group-item list-group-item-action">New Merchant</a>
                <a href="{% url 'MITReportInterface:search_transactions' %}" class="list-group-item list-group-item-action">Search Transactions</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

MITReportInterface/templates/MITReportInterface/index.html
<!Doctype html>
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<script src="{% static 'js/bootstrap.js' %}"></script>

<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>My test page</title>
    </head>
<style>
    html, body {
        height: 100%
        margin: 0;
    }
    
    body {
        display: flex;
        flex-direction: column;
        background-color: #ffffff
    }
    .content {
        flex : 1;
        display: flex;
        justify-content: center;
        align-items: center;
        background-color: white;
    }
</style>


    <body style="min-height: 100%; background-color: #000000;">
        <nav class="navbar" data-bs-theme="dark" style="background-color: #750014;">
            <div class="container-fluid">
                <a class="navbar-brand" href="https://web.mit.edu">
                    <img src="{% static 'img/mit_logo_std_rgb_white.png' %}" width="64" height="32" alt="MIT logo">
                    <span> Massachusetts Institute of Technology </span>
                </a>
            </div>
        </nav>

       
        <div style="background-color: white;">
            <a href="/web/admin/home/" class="btn btn-light position-absolute top-0 end-0 m-3">
                Go to Merchant Services Admin Homepage
            </a>
            <div class="container" style="padding: 270px;" >
                <div class="row justify-content-md-center">
                    <div class="col-lg-8">
                        <h2>Cybersource</h2>
                        <p>Enterprise Business Center Reports</p>
                    </div>
                        
                </div>
                <div class="row justify-content-md-center pb-100">
                    <div class="col-lg-8 justify-content-md-center">
                        <form name="start-form" class="" action="{% url 'MITReportInterface:reportInformation' %}">
                            <div class="row">

                                <div class="col">
                                    <input type="text" class="form-control" placeholder="Merchant ID" name="merchant_ID" required>
                                </div>
                                <div class="col">
                                    <input type="submit" class="btn btn-primary" value="continue">  
                                </div>
                                

                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
        </div>
        


        <footer style="color: #ffffff;">
            <div class="container-fluid pt-5 mx-5">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="pt-3 px-4">
                            <a href="https://mit.edu">
                                <img src="{% static 'img/mit_lockup_std-three-line_rgb_white.png' %}" width="166" height="36" alt="MIT logo">
                            </a>
                        </div>
                        
                        <div class="pt-2 px-4">
                            <p>
                                77 Massachusetts Ave, Cambridge, MA
                            </p>
                        </div>
                       

                        <div class="pt-5 pb-3 px-4">
                            <a href="https://accessibility.mit.edu" class="link-light">Accessibility</a> 
                             | 
                            <a href="https://web.mit.edu/privacy/" class="link-light"> Privacy Statement</a>
                        </div>
                    </div>

                </div>
            </div>
        </footer>
  </body>
</html>

MITReportInterface/templates/MITReportInterface/list_merchants.html
{% extends 'MITReportInterface/base.html' %}

{% block title %}List of Merchants{% endblock %}

{% block content %}
<h1>List of Merchants</h1>
<h2><button type="button" class="btn btn-secondary" onclick="location.href='{% url 'MITReportInterface:home' %}'">Return to Home</button></h2>
<table class="table table-bordered table-striped mt-3">
    <thead>
        <tr>
            <th>Actions</th>
            <th>Merchant ID</th>
            <th>Disabled</th>
            <th>Cancellation Date</th>
            <th>Secure Acceptance Status</th>
            <th>Has SA Keys</th>
            <th>Has P12 Keys</th>
            <th>Has SOAP Keys</th>
            <th>Has SCMP Keys</th>
            <th>Notes</th>
        </tr>
    </thead>
    <tbody>
        {% for merchant in merchants %}
        <tr>
            <td>
                <a href="{% url 'MITReportInterface:view_merchant' merchant.id %}" class="btn btn-sm btn-info">View</a>
            </td>
            <td>{{ merchant.id }}</td>
            <td>{{ merchant.disabled }}</td>
            <td>{{ merchant.cancellation_date }}</td>
            <td>{{ merchant.secure_acceptance_status }}</td>
            <td>{{ merchant.has_sa_keys }}</td>
            <td>{{ merchant.has_p12_keys }}</td>
            <td>{{ merchant.has_soap_keys }}</td>
            <td>{{ merchant.has_scmp_keys }}</td>
            <td>{{ merchant.notes }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block styles %}
<style>
    table.table tbody tr:nth-child(odd) {
        background-color: #f9f9f9;
    }
    table.table tbody tr:nth-child(even) {
        background-color: #ffffff;
    }
</style>
{% endblock %}

MITReportInterface/templates/MITReportInterface/new_merchant.html
{% extends 'MITReportInterface/base.html' %}

{% block title %}New Merchant{% endblock %}

{% block content %}
<h1>Add a New Merchant</h1>
<h2><button type="button" class="btn btn-secondary" onclick="location.href='{% url 'MITReportInterface:home' %}'">Return to Home</button></h2>
<form method="post" class="mt-3">
    {% csrf_token %}
    <div class="form-group mb-3">
        <label for="merchant_id">Merchant ID:</label>
        {{ form.merchant_id }}
    </div>
    <div class="form-group mb-3">
        <label for="orderpage_transaction_type">Order Page Transaction Type:</label>
        {{ form.orderpage_transaction_type }}
    </div>
    <div class="form-group mb-3">
        <label for="test_mode">Test Mode:</label>
        {{ form.test_mode }}
    </div>
    <div class="form-group form-check mb-3">
        <label for="disable_captcha" class="form-check-label">
            {{ form.disable_captcha }} Disable Captcha
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Create Merchant</button>
</form>
{% endblock %}

{% block styles %}
<style>
    .form-group, .form-check {
        margin-bottom: 1.5rem;
    }

    .form-control {
        padding: .75rem 1.25rem;
        margin-bottom: 1.5rem;
    }

    .buttonRow .btn {
        margin-right: 1rem;
    }
</style>
{% endblock %}
{% block extra_buttons %}
<button type="button" class="btn btn-secondary" onclick="location.href='{% url 'MITReportInterface:home' %}'">Return to Home</button>
{% endblock %}

MITReportInterface/templates/MITReportInterface/reportInfo.html
<!Doctype html>
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<script src="{% static 'MITReportInterface/js/bootstrap.js' %}"></script>

<html lang="en-US">
    <head>
        <meta charset="utf-8" />
        <title>Report Information Page</title>
    </head>

    <body style="min-height: 100%; background-color: #000000;" >
        <nav class="navbar" data-bs-theme="dark" style="background-color: #750014;">
            <div class="container-fluid">
                <a class="navbar-brand" href="https://web.mit.edu">
                    <img src="{% static 'img/mit_logo_std_rgb_white.png' %}" width="64" height="32" alt="MIT logo">
                    Massachusetts Institute of Technology
                </a>
            </div>
        </nav>
        
        <div style="background-color: #ffffff;">
                <div class="container" style="padding: 185px;" >
                <div class="row justify-content-md-center">
                    <div class="col-lg-6">
                        <h2>Cybersource</h2>
                        <p>Enterprise Business Center Reports</p>
                    </div>
                    
                </div>
                <div class="row justify-content-md-center pb-5">
                    <div class="col-lg-6">
                        merchant ID: {{merchantID}}
                    </div>
                </div>


                <div class="row justify-content-md-center">
                    <div class="col-lg-6">

                        <form name="date-form" class="form-horizontal" action="{% url 'MITReportInterface:reportView' %}">
                            <fieldset>
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <tbody>
                                            <tr>
                                                <td> Start Date</td>
                                                <td> End Date</td>
                                            </tr>
                                            
                                            <tr>
                                                <td>
                                                    <input type="date" class="form-control" name="start_date" required>
                                                </td>

                                                <td>
                                                    <input type="date" class="form-control" name="end_date" required>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <input type="hidden" value="{{merchantID}}" class="form-control" name="merchant_ID" required>
                                </div>
                                
                                <input type="submit" value="load" class="btn btn-primary">  
                            </fieldset>
                        </form>


                    </div>
                </div>
            </div>
        </div>
        

        <footer style="color: #ffffff;">
            <div class="container-fluid pt-5 mx-5">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="pt-3 px-4">
                            <a href="https://mit.edu">
                                <img src="{% static 'img/mit_lockup_std-three-line_rgb_white.png' %}" width="166" height="36" alt="MIT logo">
                            </a>
                        </div>
                        
                        <div class="pt-2 px-4">
                            <p>
                                77 Massachusetts Ave, Cambridge, MA
                            </p>
                        </div>
                       

                        <div class="pt-5 pb-3 px-4">
                            <a href="https://accessibility.mit.edu" class="link-light">Accessibility</a> 
                             | 
                            <a href="https://web.mit.edu/privacy/" class="link-light"> Privacy Statement</a>
                        </div>
                    </div>

                </div>
            </div>
        </footer>

    </body>

MITReportInterface/templates/MITReportInterface/test_merchants.html
{% extends 'MITReportInterface/base.html' %}

{% block title %}Test Merchant{% endblock %}

{% block content %}
<h1>Test Merchant</h1>
<h2><button type="button" class="btn btn-secondary" onclick="location.href='{% url 'MITReportInterface:home' %}'">Return to Home</button></h2>
<form method="post" novalidate>
    {% csrf_token %}
    <div class="form-group">
        {% for field in form %}
        <div class="mb-1">
            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}
                {% if field.field.required %}<span class="text-danger">*</span>{% endif %}
            </label>
            {{ field }}
            {% if field.errors %}
            <div class="text-danger">{{ field.errors }}</div>
            {% endif %}
        </div>
        {% endfor %}
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

{% block styles %}
<style>
    .form-control {
        width: 50%;
        display: inline-block;
    }
    .form-label {
        width: 50%;
    }
</style>
{% endblock %}
{% block extra_buttons %}
<button type="button" class="btn btn-secondary" onclick="location.href='{% url 'MITReportInterface:home' %}'">Return to Home</button>
{% endblock %}

MITReportInterface/templates/MITReportInterface/view_merchant.html
{% extends 'MITReportInterface/base.html' %}

{% block title %}View Merchant{% endblock %}

{% block content %}
<h1>View Merchant</h1>
<h2><button type="button" class="btn btn-secondary" onclick="location.href='{% url 'MITReportInterface:home' %}'">Return to Home</button></h2>
<h3><button type="button" class="btn btn-secondary" onclick="location.href='{% url 'MITReportInterface:list_merchants' %}'">Return to List</button></h3>
<table class="table table-bordered">
    <tr>
        <th>Merchant ID</th>
        <td>{{ merchant.id }}</td>
    </tr>
    <tr>
        <th>Disabled</th>
        <td>{{ merchant.disabled }}</td>
    </tr>
    <tr>
        <th>Cancellation Date</th>
        <td>{{ merchant.cancellation_date }}</td>
    </tr>
    <tr>
        <th>Secure Acceptance Status</th>
        <td>{{ merchant.secure_acceptance_status }}</td>
    </tr>
    <tr>
        <th>Has SA Keys</th>
        <td>{{ merchant.has_sa_keys }}</td>
    </tr>
    <tr>
        <th>Has P12 Keys</th>
        <td>{{ merchant.has_p12_keys }}</td>
    </tr>
    <tr>
        <th>Has SOAP Keys</th>
        <td>{{ merchant.has_soap_keys }}</td>
    </tr>
    <tr>
        <th>Has SCMP Keys</th>
        <td>{{ merchant.has_scmp_keys }}</td>
    </tr>
    <tr>
        <th>Notes</th>
        <td>{{ merchant.notes }}</td>
    </tr>
</table>
<a href="{% url 'MITReportInterface:list_merchants' %}" class="btn btn-secondary">Back to List</a>
{% endblock %}
{% block extra_buttons %}
<button type="button" class="btn btn-secondary" onclick="location.href='{% url 'MITReportInterface:home' %}'">Return to Home</button>
{% endblock %}